### PR TITLE
[continuous-deploy-fingeprint] Output whether each platform build was created or one was reused

### LINKED ISSUE #290: continuous-deploy-fingerprint outputs build ids even if no one was started
### Description of the bug
After running continuous-deploy-fingerprint I have in the outputs the build ids for both platforms, even if they are old ones, no one was started

### To Reproduce
Setup continuous-deploy-fingerprint on a project an run the workflow twice

#### Expected behavior
It is expected (as docs says) to only have the outputs `android-build-id` and `ios-build-id` when they have been started in this run

#### Actual behavior
Always have the outputs `android-build-id` and `ios-build-id`

### PR DESCRIPTION
**Pull request by wschurman**
### Linked issue

Closes #290.
Closes ENG-13543.

### Additional context

Showing whether the run of the action started a new build can be useful for next steps in the workflow. This makes this change and outputs the info and does some slight refactors to make things more type safe.

### CODE REVIEW

**Comment by wschurman** [comment]
* **#306** <a href="https://app.graphite.dev/github/pr/expo/expo-github-action/306?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @wschurman and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

File: src/actions/continuous-deploy-fingerprint.ts [hunk 1]
```diff
@@ -41,40 +43,48 @@ export async function continuousDeployFingerprintAction(input = collectContinuou
...
+  if (existingIosBuildInfo) {
+    info(`Existing iOS build found with matching fingerprint: ${existingIosBuildInfo.id}`);
+    iosBuildRunInfo = { buildInfo: existingIosBuildInfo, isNew: false };
   } else {
     info(`No existing iOS build found for fingerprint, starting a new build...`);
-    iosBuildInfo = await createEASBuildAsync({ cwd: input.workingDirectory, platform: 'ios', profile: input.profile });
+    iosBuildRunInfo = {
+      buildInfo: await createEASBuildAsync({ cwd: input.workingDirectory, platform: 'ios', profile: input.profile }),
+      isNew: true,
+    };
```
Comment (Kudo) [inline src/actions/continuous-deploy-fingerprint.ts:85]:
```suggestion
    iosBuildRunInfo = {
      buildInfo: await createEASBuildAsync({
        cwd: input.workingDirectory,
        platform: 'ios',
        profile: input.profile,
      }),
      isNew: true,
    };
```

nit: indent as android

**Review by Kudo — APPROVED** [review]
